# Generated by Django 4.2.28 on 2026-03-02 12:25

from django.db import migrations
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country_of_residence',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
