# Generated by Django 4.2.28 on 2026-03-03 18:24

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_country_of_residence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAccount',
            fields=[
            ],
            options={
                'verbose_name': 'Staff Account',
                'verbose_name_plural': 'Staff Accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
    ]
