# Generated by Django 4.2.28 on 2026-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='tip',
            field=models.CharField(blank=True, help_text='Conseil affiche aux etudiants, ex: "Assurez-vous que le scan est lisible"', max_length=255),
        ),
    ]
