# Generated by Django 4.2.29 on 2026-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NextStepFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (0, 1, 2...)")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ NextStep',
                'verbose_name_plural': 'FAQs NextStep',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NextStepService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text="Nom de l'icône (ex: icon_target.png) ou chemin", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service NextStep',
                'verbose_name_plural': 'Services NextStep',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NextStepSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo principal de NextStep', null=True, upload_to='nextstep/logos/')),
                ('appointment_url', models.URLField(blank=True, help_text="Lien pour 'Prendre Rendez-vous' (ex: Calendly)")),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NextStep Setting',
                'verbose_name_plural': 'NextStep Settings',
            },
        ),
        migrations.CreateModel(
            name='NextStepTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('program', models.CharField(help_text='ex: Master Informatique à la Sorbonne', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='nextstep/testimonials/')),
                ('rating', models.IntegerField(default=5, help_text='Note sur 5')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Témoignage NextStep',
                'verbose_name_plural': 'Témoignages NextStep',
            },
        ),
    ]
