# Generated by Django 4.2.29 on 2026-07-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextstepsettings',
            name='address',
            field=models.TextField(blank=True, help_text='Adresse physique'),
        ),
        migrations.AddField(
            model_name='nextstepsettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Adresse email de contact', max_length=254),
        ),
        migrations.AddField(
            model_name='nextstepsettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Numéro de téléphone de contact', max_length=20),
        ),
    ]
