# Generated by Django 4.2.29 on 2026-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0002_nextstepsettings_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusFrancePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Procédure Campus France', max_length=255)),
                ('description', models.TextField(blank=True, default="Tout ce qu'il faut savoir sur la procédure Campus France.")),
            ],
            options={
                'verbose_name': 'Nextstep - Page Campus France',
                'verbose_name_plural': 'Nextstep - Page Campus France',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contactez-nous', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Nous sommes à votre écoute.')),
            ],
            options={
                'verbose_name': 'Nextstep - Page Contact',
                'verbose_name_plural': 'Nextstep - Page Contact',
            },
        ),
        migrations.CreateModel(
            name='FAQPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Foire Aux Questions', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Les réponses à vos questions les plus fréquentes.')),
            ],
            options={
                'verbose_name': 'Nextstep - Page FAQ',
                'verbose_name_plural': 'Nextstep - Page FAQ',
            },
        ),
        migrations.CreateModel(
            name='MentionsLegalesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Mentions Légales', max_length=255)),
                ('content', models.TextField(blank=True, default='Contenu des mentions légales de NextStep Consulting.')),
            ],
            options={
                'verbose_name': 'Nextstep - Page Mentions Légales',
                'verbose_name_plural': 'Nextstep - Page Mentions Légales',
            },
        ),
        migrations.CreateModel(
            name='NextstepHomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Bienvenue chez NextStep Consulting', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Votre partenaire de confiance pour réussir vos études en France.')),
                ('hero_button_text', models.CharField(default='Découvrir nos services', max_length=50)),
                ('hero_button_link', models.CharField(default='#services', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='nextstep/home/')),
                ('about_title', models.CharField(default='À Propos de Nous', max_length=255)),
                ('about_text', models.TextField(blank=True, default="Nous sommes une équipe d'experts dédiés à la réussite de votre mobilité internationale.")),
                ('why_us_title', models.CharField(default='Pourquoi nous choisir ?', max_length=255)),
                ('why_us_text', models.TextField(blank=True, default='Un accompagnement personnalisé et une expertise reconnue.')),
            ],
            options={
                'verbose_name': 'Nextstep - Paramètres Accueil',
                'verbose_name_plural': 'Nextstep - Paramètres Accueil',
            },
        ),
        migrations.AlterModelOptions(
            name='nextstepfaq',
            options={'ordering': ['order'], 'verbose_name': 'Nextstep - Paramètres FAQ', 'verbose_name_plural': 'Nextstep - Paramètres FAQs'},
        ),
        migrations.AlterModelOptions(
            name='nextstepservice',
            options={'ordering': ['order'], 'verbose_name': 'Nextstep - Accueil Service', 'verbose_name_plural': 'Nextstep - Accueil Services'},
        ),
        migrations.AlterModelOptions(
            name='nextstepsettings',
            options={'verbose_name': 'Nextstep Consulting - Paramètres Globaux', 'verbose_name_plural': 'Nextstep Consulting - Paramètres Globaux'},
        ),
        migrations.AlterModelOptions(
            name='nextsteptestimonial',
            options={'verbose_name': 'Nextstep - Accueil Témoignage', 'verbose_name_plural': 'Nextstep - Accueil Témoignages'},
        ),
        migrations.AddField(
            model_name='nextstepsettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text="Favicon (icône d'onglet)", null=True, upload_to='nextstep/logos/'),
        ),
    ]
