# Generated by Django 4.2.29 on 2026-07-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0003_campusfrancepagesettings_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NextStepAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, help_text="Télécharger l'icône de l'avantage (Image ou SVG)", null=True, upload_to='nextstep/advantages/')),
                ('icon_name', models.CharField(blank=True, help_text="Nom de l'icône statique (ex: icon_target.png, facultatif si image chargée)", max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nextstep - Accueil Avantage',
                'verbose_name_plural': 'Nextstep - Accueil Avantages',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='nextstepservice',
            options={'ordering': ['order'], 'verbose_name': "Nextstep - Domaine d'expertise", 'verbose_name_plural': "Nextstep - Domaines d'expertise"},
        ),
        migrations.AddField(
            model_name='nextstephomepagesettings',
            name='service_phare_button_link',
            field=models.CharField(default='https://visa.nextstepc.com', max_length=255),
        ),
        migrations.AddField(
            model_name='nextstephomepagesettings',
            name='service_phare_button_text',
            field=models.CharField(default="Découvrir l'accompagnement", max_length=100),
        ),
        migrations.AddField(
            model_name='nextstephomepagesettings',
            name='service_phare_description',
            field=models.TextField(default="Vous rêvez d'étudier en France ? Nous vous accompagnons de A à Z : choix de l'établissement, procédure Campus France, demande de visa, et préparation au départ. Mettez toutes les chances de votre côté avec notre équipe d'experts."),
        ),
        migrations.AddField(
            model_name='nextstephomepagesettings',
            name='service_phare_image',
            field=models.ImageField(blank=True, help_text="Image d'illustration du service phare (droite)", null=True, upload_to='nextstep/home/'),
        ),
        migrations.AddField(
            model_name='nextstephomepagesettings',
            name='service_phare_title',
            field=models.CharField(default='Notre service phare : Campus France', max_length=255),
        ),
        migrations.AddField(
            model_name='nextstepservice',
            name='icon',
            field=models.ImageField(blank=True, help_text="Télécharger l'icône de l'expertise (Image ou SVG)", null=True, upload_to='nextstep/services/'),
        ),
        migrations.AlterField(
            model_name='nextstepservice',
            name='icon_name',
            field=models.CharField(blank=True, help_text="Nom de l'icône statique (ex: icon_target.png, facultatif si image chargée)", max_length=100),
        ),
    ]
