# Generated by Django 4.2.29 on 2026-07-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nextstep', '0004_nextstepadvantage_alter_nextstepservice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='description',
            field=models.TextField(blank=True, default="Vous avez un projet en tête ou souhaitez en savoir plus sur nos services ? N'hésitez pas à nous contacter, notre équipe vous répondra dans les plus brefs délais."),
        ),
    ]
