# Generated by Django 4.2.28 on 2026-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_payment_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mtn', 'MTN Mobile Money'), ('orange', 'Orange Money'), ('moov', 'Moov Money'), ('celtiis', 'Celtiis Money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('expired', 'Expire'), ('cancelled', 'Annule')], default='pending', max_length=20),
        ),
    ]
