# Generated by Django 4.2.28 on 2026-03-01 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_status', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('in_process', 'In Process')], max_length=20)),
                ('education_level', models.CharField(blank=True, choices=[('high_school', 'High School'), ('bachelor', 'Bachelor'), ('master', 'Master')], max_length=20)),
                ('admission_status', models.CharField(blank=True, choices=[('admitted', 'Already Admitted'), ('applied', 'Applied'), ('not_applied', 'Not Applied')], max_length=20)),
                ('campus_france_account', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=5)),
                ('visa_support', models.CharField(blank=True, choices=[('full', 'Full Assistance'), ('review', 'Review Only'), ('none', 'No Help Needed')], max_length=20)),
                ('financial_situation', models.CharField(blank=True, choices=[('own_funds', 'Own Funds'), ('sponsor', 'Sponsor'), ('not_ready', 'Not Ready')], max_length=20)),
                ('timeline', models.CharField(blank=True, choices=[('less_3', 'Less than 3 months'), ('3_to_6', '3-6 months'), ('more_6', '6+ months')], max_length=20)),
                ('basic_score', models.IntegerField(default=0)),
                ('standard_score', models.IntegerField(default=0)),
                ('premium_score', models.IntegerField(default=0)),
                ('recommended_plan', models.CharField(blank=True, max_length=20)),
                ('needs_assistance', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
