# Generated by Django 4.2.29 on 2026-07-01 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie FAQ',
                'verbose_name_plural': 'Catégories FAQ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la section (ex: Éditeur du site)')),
                ('content', models.TextField(verbose_name='Contenu de la section')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Mention Légale',
                'verbose_name_plural': 'Mentions Légales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Logo du site', null=True, upload_to='site/')),
                ('rendez_vous_link', models.URLField(blank=True, help_text='Lien pour prendre rendez-vous')),
                ('contact_email', models.EmailField(blank=True, help_text='Email de contact global', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Téléphone de contact', max_length=20)),
                ('contact_address', models.TextField(blank=True, help_text='Adresse du cabinet')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(verbose_name='Réponse')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.faqcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Question FAQ',
                'verbose_name_plural': 'Questions FAQ',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
