# Generated by Django 4.2.29 on 2026-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='LegalMention',
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Paramètre du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='rendez_vous_link',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, default='10 Rue de la Paix, 75002 Paris, France', help_text='Adresse physique'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Lien vers la page Facebook'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Lien vers le compte Instagram'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_link',
            field=models.URLField(blank=True, help_text='Lien vers la page LinkedIn'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Lien vers le compte Twitter/X'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='support@visanexstep.com', help_text='Email de contact principal', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+33 1 23 45 67 89', help_text='Numéro de téléphone de contact', max_length=20),
        ),
        migrations.DeleteModel(
            name='FAQCategory',
        ),
        migrations.DeleteModel(
            name='FAQItem',
        ),
    ]
