# Generated by Django 4.2.29 on 2026-07-06 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_faqitem_category_delete_legalmention_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(blank=True, help_text="Code SVG de l'icône")),
                ('is_highlighted', models.BooleanField(default=False, help_text='Mettre en évidence (carte différente)')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Avantage',
                'verbose_name_plural': 'Avantages',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Icone ou image', null=True, upload_to='features/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fonctionnalité',
                'verbose_name_plural': 'Fonctionnalités',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Votre parcours pour étudier en France commence ici', max_length=255)),
                ('hero_subtitle', models.TextField(default="De l'inscription Campus France à l'obtention du visa — nous vous guidons à chaque étape avec un accompagnement personnalisé.")),
                ('hero_primary_button_text', models.CharField(default='Démarrer mon dossier', max_length=50)),
                ('hero_primary_button_link', models.CharField(default='account_signup', help_text='Nom de la vue (ex: account_signup) ou URL absolue', max_length=200)),
                ('hero_secondary_button_text', models.CharField(default='Comment ça marche', max_length=50)),
                ('hero_secondary_button_link', models.CharField(default='#processus', max_length=200)),
                ('presentation_title', models.CharField(default="Finis les dossiers papiers et l'incertitude.", max_length=255)),
                ('presentation_description', models.TextField(default='Visanexstep à été conçu pour révolutionner la manière dont les étudiants préparent leur départ pour la France.')),
                ('features_subtitle', models.CharField(default='Fonctionnalités clés', max_length=100)),
                ('features_title', models.CharField(default='Tout ce dont vous avez besoin, au même endroit.', max_length=255)),
                ('features_description', models.TextField(default="Une suite d'outils pensée spécifiquement pour la réussite de votre mobilité étudiante.")),
                ('process_title', models.CharField(default='4 étapes pour décrocher votre visa', max_length=255)),
                ('process_description', models.TextField(default='Un processus clair, digitalisé et structuré pour garantir votre succès.')),
                ('advantages_subtitle', models.CharField(default="L'avantage Visanexstep", max_length=100)),
                ('advantages_title', models.CharField(default='Mettez toutes les chances de votre côté.', max_length=255)),
                ('advantages_description_1', models.TextField(default='Une demande de visa étudiant est un parcours complexe où la moindre erreur peut être fatale. Nous éliminons ce risque.')),
                ('advantages_description_2', models.TextField(default="Notre approche hybride (SaaS + Humain) vous permet de rester autonome tout en bénéficiant de l'œil expert de professionnels à chaque étape clé. Vous n'êtes plus jamais seul face à vos démarches.")),
                ('testimonials_title', models.CharField(default='Ils ont réussi avec Visanexstep', max_length=255)),
                ('cta_title', models.CharField(default="Prêt à transformer votre projet d'études en réalité ?", max_length=255)),
                ('cta_subtitle', models.TextField(default="Rejoignez des centaines d'étudiants qui ont choisi la sérénité avec Visanexstep.")),
                ('cta_button_text', models.CharField(default='Créer mon compte gratuitement', max_length=50)),
                ('cta_button_link', models.CharField(default='account_signup', max_length=200)),
                ('cta_subtext', models.CharField(default="Aucune carte de crédit requise pour s'inscrire.", max_length=255)),
            ],
            options={
                'verbose_name': 'Page Accueil - Paramètres',
                'verbose_name_plural': 'Page Accueil - Paramètres',
            },
        ),
        migrations.CreateModel(
            name='PresentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Présentation - Élément',
                'verbose_name_plural': 'Présentation - Éléments',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text="Numéro de l'étape")),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Étape de processus',
                'verbose_name_plural': 'Étapes de processus',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(help_text='Ex: Master Finance, Paris', max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
                'ordering': ['order'],
            },
        ),
    ]
