# Generated by Django 4.2.29 on 2026-07-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_advantageitem_featureitem_homepagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='À propos de Visanexstep', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Découvrez notre histoire et notre mission.')),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Visanexstep - Page À Propos',
                'verbose_name_plural': 'Visanexstep - Page À Propos',
            },
        ),
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contactez-nous', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Nous sommes là pour vous aider.')),
            ],
            options={
                'verbose_name': 'Visanexstep - Page Contact',
                'verbose_name_plural': 'Visanexstep - Page Contact',
            },
        ),
        migrations.CreateModel(
            name='FAQPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Foire Aux Questions', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Trouvez les réponses à vos questions.')),
            ],
            options={
                'verbose_name': 'Visanexstep - Page FAQ',
                'verbose_name_plural': 'Visanexstep - Page FAQ',
            },
        ),
        migrations.CreateModel(
            name='HowItWorksPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Comment ça marche', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Notre processus détaillé de A à Z.')),
            ],
            options={
                'verbose_name': 'Visanexstep - Page Processus',
                'verbose_name_plural': 'Visanexstep - Page Processus',
            },
        ),
        migrations.CreateModel(
            name='PricingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Tarifs', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Choisissez le plan qui vous correspond.')),
            ],
            options={
                'verbose_name': 'Visanexstep - Page Tarifs',
                'verbose_name_plural': 'Visanexstep - Page Tarifs',
            },
        ),
        migrations.CreateModel(
            name='ServicesPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nos Services', max_length=255)),
                ('subtitle', models.TextField(blank=True, default="Des solutions sur mesure pour votre projet d'études.")),
            ],
            options={
                'verbose_name': 'Visanexstep - Page Services',
                'verbose_name_plural': 'Visanexstep - Page Services',
            },
        ),
        migrations.CreateModel(
            name='TestimonialsPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Témoignages', max_length=255)),
                ('subtitle', models.TextField(blank=True, default='Ce que nos étudiants disent de nous.')),
            ],
            options={
                'verbose_name': 'Visanexstep - Page Témoignages',
                'verbose_name_plural': 'Visanexstep - Page Témoignages',
            },
        ),
        migrations.AlterModelOptions(
            name='advantageitem',
            options={'ordering': ['order'], 'verbose_name': 'Visanexstep - Accueil Avantage', 'verbose_name_plural': 'Visanexstep - Accueil Avantages'},
        ),
        migrations.AlterModelOptions(
            name='featureitem',
            options={'ordering': ['order'], 'verbose_name': 'Visanexstep - Accueil Fonctionnalité', 'verbose_name_plural': 'Visanexstep - Accueil Fonctionnalités'},
        ),
        migrations.AlterModelOptions(
            name='homepagesettings',
            options={'verbose_name': 'Visanexstep - Accueil Paramètres', 'verbose_name_plural': 'Visanexstep - Accueil Paramètres'},
        ),
        migrations.AlterModelOptions(
            name='presentationitem',
            options={'ordering': ['order'], 'verbose_name': 'Visanexstep - Accueil Présentation', 'verbose_name_plural': 'Visanexstep - Accueil Présentation'},
        ),
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ['order'], 'verbose_name': 'Visanexstep - Accueil Processus', 'verbose_name_plural': 'Visanexstep - Accueil Processus'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Visanexstep - Paramètres Globaux', 'verbose_name_plural': 'Visanexstep - Paramètres Globaux'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': 'Visanexstep - Accueil Témoignage', 'verbose_name_plural': 'Visanexstep - Accueil Témoignages'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text="Favicon (icône d'onglet)", null=True, upload_to='visanexstep/branding/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo principal', null=True, upload_to='visanexstep/branding/'),
        ),
    ]
