# Generated by Django 4.2.29 on 2026-07-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_aboutpagesettings_contactpagesettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la fonctionnalité')),
                ('basic_value', models.CharField(blank=True, max_length=100, verbose_name="Valeur pour Essentiel (ex: 'Oui', 'Non', '1 seule fois')")),
                ('premium_value', models.CharField(blank=True, max_length=100, verbose_name='Valeur pour Premium')),
                ('excellence_value', models.CharField(blank=True, max_length=100, verbose_name='Valeur pour Excellence')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Visanexstep - Tarifs Comparatif',
                'verbose_name_plural': 'Visanexstep - Tarifs Comparatifs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'offre")),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.CharField(max_length=50, verbose_name='Prix (ex: 49€ ou Sur devis)')),
                ('button_text', models.CharField(max_length=100, verbose_name='Texte du bouton')),
                ('button_link', models.CharField(default='#', max_length=255, verbose_name='Lien du bouton')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Plus populaire')),
                ('features_list', models.TextField(help_text="Une fonctionnalité par ligne. Précéder d'un '-' (ex: - Accès à la plateforme). Pour barrer/désactiver, précéder d'un 'x' (ex: x Chat en temps réel).", verbose_name='Liste des fonctionnalités')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Visanexstep - Tarifs Offre',
                'verbose_name_plural': 'Visanexstep - Tarifs Offres',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricingpagesettings',
            options={'verbose_name': 'Visanexstep - Page Tarifs - Paramètres', 'verbose_name_plural': 'Visanexstep - Page Tarifs - Paramètres'},
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='cta_button_link',
            field=models.CharField(default='pages:contact', max_length=255),
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='cta_button_text',
            field=models.CharField(default='Contacter un conseiller', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='cta_subtitle',
            field=models.TextField(blank=True, default='Notre équipe est là pour vous guider vers la meilleure formule pour votre profil.'),
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='cta_title',
            field=models.CharField(default='Encore des questions sur nos tarifs ?', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricingpagesettings',
            name='subtitle',
            field=models.TextField(blank=True, default="Choisissez l'offre qui correspond à vos besoins et bénéficiez de l'accompagnement idéal pour vos études en France."),
        ),
        migrations.AlterField(
            model_name='pricingpagesettings',
            name='title',
            field=models.CharField(default='Un tarif transparent.<br/>Zéro surprise.', max_length=255),
        ),
    ]
