# Generated by Django 4.2.29 on 2026-07-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pricingfeature_pricingplan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingpagesettings',
            old_name='cta_button_link',
            new_name='button_link',
        ),
        migrations.RemoveField(
            model_name='pricingpagesettings',
            name='cta_button_text',
        ),
        migrations.RemoveField(
            model_name='pricingpagesettings',
            name='cta_subtitle',
        ),
        migrations.RemoveField(
            model_name='pricingpagesettings',
            name='cta_title',
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='button_text',
            field=models.CharField(default='Contactez-nous', max_length=100),
        ),
        migrations.AddField(
            model_name='pricingpagesettings',
            name='description',
            field=models.TextField(blank=True, default="Nous proposons un accompagnement personnalisé et adapté à chaque profil d'étudiant. Nos tarifs sont établis sur mesure en fonction de la complexité de votre dossier, de vos besoins en coaching, et des services spécifiques demandés. Contactez-nous pour obtenir un devis gratuit et personnalisé."),
        ),
        migrations.AlterField(
            model_name='pricingpagesettings',
            name='subtitle',
            field=models.TextField(blank=True, default="Découvrez nos conditions d'accompagnement pour vos études en France."),
        ),
        migrations.AlterField(
            model_name='pricingpagesettings',
            name='title',
            field=models.CharField(default='Un tarif transparent. Zéro surprise.', max_length=255),
        ),
    ]
