# Generated by Django 4.2.28 on 2026-03-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='calendar_link',
            field=models.URLField(blank=True),
        ),
    ]
